name: Secret Demo

on:
  push:
    branches:
      - main

jobs:
  secret-demo-job:
    runs-on: ubuntu-latest
    steps:
      - name: Accessing Secret
        run: echo "The secret value is: ${{ secrets.DOCKER_USERNAME }}"
               echo "The secret value is: ${{ secrets.DOCKER_PASSWORD }}"